# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniai',
                'doc_host': 'https://fromLittleAcorns.github.io',
                'git_url': 'https://github.com/fromLittleAcorns/miniai',
                'lib_path': 'miniai'},
  'syms': { 'miniai.core': { 'miniai.core.foo': ('core.html#foo', 'miniai/core.py'),
                             'miniai.core.say_hello': ('core.html#say_hello', 'miniai/core.py')},
            'miniai.datasets': { 'miniai.datasets.collate_dict': ('datasets.html#collate_dict', 'miniai/datasets.py'),
                                 'miniai.datasets.inplace': ('datasets.html#inplace', 'miniai/datasets.py')},
            'miniai.plotting': { 'miniai.plotting.get_grid': ('plotting.html#get_grid', 'miniai/plotting.py'),
                                 'miniai.plotting.show_image': ('plotting.html#show_image', 'miniai/plotting.py'),
                                 'miniai.plotting.show_images': ('plotting.html#show_images', 'miniai/plotting.py'),
                                 'miniai.plotting.subplots': ('plotting.html#subplots', 'miniai/plotting.py')},
            'miniai.utils': { 'miniai.utils.collate_device': ('utils.html#collate_device', 'miniai/utils.py'),
                              'miniai.utils.to_device': ('utils.html#to_device', 'miniai/utils.py')}}}
