# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_core.ipynb 2
from fastcore.test import *

# %% ../nbs/00_core.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_core.ipynb 7
def foo(): pass
